# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b2eae72882d84296f045eec5f979b3f2e96cb0b466079d6a91ddbe9a87879020b978ff45f035992f276511994669ed6be5d0532a1d64b2f8a7822d6ef5c7a06

test:
  secret_key_base: f742921bd2c49dc16b2b2fb95c955532681fac26bb1b777fc84c1f39e7a1355b85e471486c61058136e0ab8c469bd4a3d3c484811fa5b19696b71572a8b86d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
